### PR TITLE
Added Features and Styling

### PR DESCRIPTION
**Pull request by parthtaneja0001**
I have added a help button and a FAQ's button and changed the styling for better user experience .
This is an image foir your reference.
Screenshot 2024-10-14 at 1 25 16 AM
Please review the changes and update me if any changes are required or consider merging my pr.
Thanks!

### CODE REVIEW

**Comment by Abhilash107** [comment]
@parthtaneja0001 Kindly mention the issue that you have fixed/resolved.
For example:- fixes #xyz issue

**Comment by parthtaneja0001** [comment]
hey @Abhilash107 I have added the FAQ's and help feature along with icons changed the font to make the website attractive and also fixed a typo of dashboard

**Comment by Abhilash107** [comment]
@parthtaneja0001 ok I get it, however add the issue tag number

**Comment by parthtaneja0001** [comment]
The issue number is #2

**Comment by Abhilash107** [comment]
> The issue number is #2

@parthtaneja0001 Hey there! Don't forget to star the repository and give me a follow!

**Pull request merged**
