### PR TITLE
Add Faq Page

### PR DESCRIPTION
**Pull request by Priyanshu-su30**
Add FAQ page to the FAQ Section.
Solves: #39 
Here's the preview
Screenshot (250)

### CODE REVIEW

**Comment by Priyanshu-su30** [comment]
Hey @Abhilash107 , Can you check.

**Comment by Abhilash107** [comment]
> Hey @Abhilash107 , Can you check.

It looks good, however it would be better with outlines/borders.

**Comment by Priyanshu-su30** [comment]
Sure I'll add borders

**Comment by Priyanshu-su30** [comment]
Hey @Abhilash107, The borders are added pls take a look.

**Comment by Abhilash107** [comment]
> Hey @Abhilash107, The borders are added pls take a look.

Could you please share any screenshots of the changes made?

**Comment by Priyanshu-su30** [comment]
Here's the preview of the changes made
Screenshot (264)

**Pull request merged**
