### PR TITLE
Updated TYPO of DashBoard

### PR DESCRIPTION
**Pull request by sambhavbohra**
I have checked and got to know the issue of TYPO in dashboard and **updated it to Dashboard**

### CODE REVIEW

**Comment by sambhavbohra** [comment]
Please merge it as soon as possible it will be very helpful

**Comment by parthtaneja0001** [comment]
ive already done that in my pr before you bro

**Comment by Abhilash107** [comment]
@sambhavbohra Kindly mention the issue that you have fixed/resolved.
For example:- fixes #xyz issue

**Comment by pa1narendra** [comment]
@sambhavbohra I need your help

**Comment by sambhavbohra** [comment]
yes say me @pa1narendra

**Comment by pa1narendra** [comment]
You worked on ai-course-generator right

**Comment by pa1narendra** [comment]
@sambhavbohra  I messaged you on discord can you please check

**Pull request closed without merging**
