### PR TITLE
UI improve

### PR DESCRIPTION
**Pull request by Somgester**
i have added some animations to fa-icons, improved styling, added static user icon with image and logout button, and some hover effects too.

screenshot attached:

 
Screenshot 2024-10-14 174450

### CODE REVIEW

**Comment by Abhilash107** [comment]
Hey @Somgester , please include the issue tag that you have resolved.

**Comment by Somgester** [comment]
issues resolved:
#12 Add User Profile Section.
#27 Enhance UI design for better User Experience.
#15 change twitter logo to new logo('X').
#39 Add FAQs section to the project.

**Comment by Abhilash107** [comment]
> issues resolved: #12 Add User Profile Section. #27 Enhance UI design for better User Experience. #15 change twitter logo to new logo('X'). #39 Add FAQs section to the project.

OK, but this operates on a first-come, first-served basis. You need to be assigned an issue before making a PR.

**Comment by Somgester** [comment]
so, just assign me those issues and merge it.
or what can i do now?

**Comment by Abhilash107** [comment]
> so, just assign me those issues and merge it.
> or what can i do now?
> 

You can explore the project and find new issues or enhancements,and raise a new issue.

**Pull request closed without merging**
