### PR TITLE
SUBMITTED

### PR DESCRIPTION
**Pull request by Swastik200**
PLEASE CHECK AND CONFIRM
SIDE MENUBAR
SB1

### CODE REVIEW

**Comment by Abhilash107** [comment]
Hey @Swastik200, this UO looks nice, but your changes have altered the previous Ui which was better, so try to add the button functionality you mentioned in the issue.

**Comment by Swastik200** [comment]
Ok

**Comment by Abhilash107** [comment]
> ISSUE #18 SUBMITTED

Could u pls share the screenshot?

**Comment by Swastik200** [comment]
SB1

**Pull request closed without merging**
