### PR TITLE
Feedback form created

### LINKED ISSUE #5: ADD FEEDBACK FORM
Feedback form not available 
So I would like to help you out and create a feedback with you social media links and ask user about their data

### PR DESCRIPTION
**Pull request by sambhavbohra**
created the feedback form !! 
**FIXES #5**   

##Screenshot
Screenshot 2024-10-15 000606
Screenshot 2024-10-15 000616

### CODE REVIEW

**Comment by Abhilash107** [comment]
Hey @sambhavbohra , I noticed that you have been spamming in the issue section and are unable to create a feedback form that aligns with the main page.

**Comment by Sauhard74** [comment]
> Hey @sambhavbohra , I noticed that you have been spamming in the issue section and are unable to create a feedback form that aligns with the main page.

If you don't want people to work on you repo and contribute its very easy just cut down your repo as a open source project and build it by your own , I checked @sambhavbohra work and it seems pretty well going with the theme and responsive feedback form 

without discussing on the changes and issue you closed the request ? don't disrespect developers who are helping you build your platform 

I highly condemn that

**Comment by Abhilash107** [comment]
> > Hey @sambhavbohra , I noticed that you have been spamming in the issue section and are unable to create a feedback form that aligns with the main page.
> 
> If you don't want people to work on you repo and contribute its very easy just cut down your repo as a open source project and build it by your own , I checked @sambhavbohra work and it seems pretty well going with the theme and responsive feedback form 
> 
> without discussing on the changes and issue you closed the request ? don't disrespect developers who are helping you build your platform 
> 
> I highly condemn that 

I think u haven't checked the discussion tab yet. 
And yes this Ui doesn't align with the main page. 
The above person u tagged was just raising issues (4-5) . So if u have any doubt, feel free to reach me.

**Comment by Abhilash107** [comment]
> > Hey @sambhavbohra , I noticed that you have been spamming in the issue section and are unable to create a feedback form that aligns with the main page.
> 
> If you don't want people to work on you repo and contribute its very easy just cut down your repo as a open source project and build it by your own , I checked @sambhavbohra work and it seems pretty well going with the theme and responsive feedback form 
> 
> without discussing on the changes and issue you closed the request ? don't disrespect developers who are helping you build your platform 
> 
> I highly condemn that 

And as in the 2nd para you have mentioned, yes That was my bad, thanks for rectifying me.

**Comment by Abhilash107** [comment]
@sambhavbohra try to fix it, such as the placement of content and font colors too.

**Comment by sambhavbohra** [comment]
Working on it !!

**Comment by Abhilash107** [comment]
Hey @sambhavbohra, the colors don't match the background of the main page.

**Comment by Abhilash107** [comment]
> Hey @sambhavbohra, the colors don't match the background of the main page.

the light brown bg color of the form.

**Comment by sambhavbohra** [comment]
fixed as per your requirement 
#screenshot
Screenshot 2024-10-16 200341

**Comment by sambhavbohra** [comment]
Hey if you okay with I need update it !! 
Unmerge this I will update this design then you can update it !!

**Comment by Abhilash107** [comment]
> Hey if you okay with I need update it !! Unmerge this I will update this design then you can update it !!

No, it's done. Btw thanks for your contribution.

**Comment by sambhavbohra** [comment]
no issues !!

**Pull request merged**
