### PR TITLE
Enhance Login and Signup Interfaces with Navigation Bar and Modern Design

### PR DESCRIPTION
**Pull request by Abhishek-IITP**
I would like to propose an enhancement for our open contribution platform regarding the login and signup interfaces. Currently, the user experience when trying to access these features is not available.

### Key Points:

- **Absence of Navigation Bar**: The lack of a navigation bar on the site can lead to confusion for new users trying to sign up or log in. This PR introduces a clear navigation bar that guides users through the signup and login processes.

- **Modern Design**: A modern, aesthetically pleasing design has been implemented to significantly improve user engagement. This includes:
  - Clean input fields with icons.
  - Distinctive buttons with hover effects.
  - Clear messaging that indicates transitions between login and signup forms.
  - A background that matches the overall theme of the site, enhancing the visual appeal.

I believe these changes will greatly enhance the user experience and look forward to your feedback!

Screenshot 2024-10-14 170638

### CODE REVIEW

**Comment by Abhishek-IITP** [comment]
@Abhilash107 yes

**Comment by Abhishek-IITP** [comment]
@Abhilash107  Could you tell me what kind of website this is so I can design a feedback form for you too?

**Comment by Abhishek-IITP** [comment]
"Can you add the Hacktoberfest label to it? It would mean a lot to me if you could."

**Comment by Abhilash107** [comment]
> @Abhilash107 yes

Hey there! Don't forget to star the repository and give me a follow!

**Pull request merged**
