### PR TITLE
Add Responsive Contact Us Page for Sidebar

### LINKED ISSUE #20: Add Modern Contact Page
Contact Page not available.
So I would like to help you out in creating a Modern Contact Page.
Sample pic-
Screenshot 2024-10-14 104503

Please assign this to me and mark it as hactoberfest.

### PR DESCRIPTION
**Pull request by Abhi-Jeeet**
Fixed #20 

This pull request introduces a responsive "Contact Us" page for the Sidebar website. The page has been designed to provide a smooth user experience and features an improved background for enhanced aesthetics.

Features:

1. Fully responsive design that adapts to different screen sizes.
2. Intuitive layout for users to easily reach out.
3. Enhanced visual appeal with a modern background and styling

Screenshot 2024-10-14 161127

Awaiting feedback for any additional improvements or suggestions.

### CODE REVIEW

**Comment by Abhilash107** [comment]
> Fixed #20
> 
> This pull request introduces a responsive "Contact Us" page for the Sidebar website. The page has been designed to provide a smooth user experience and features an improved background for enhanced aesthetics.
> 
> Features:
> 
> 1. Fully responsive design that adapts to different screen sizes.
> 2. Intuitive layout for users to easily reach out.
> 3. Enhanced visual appeal with a modern background and styling
> 
> Screenshot 2024-10-14 161127
> 
> Awaiting feedback for any additional improvements or suggestions.

@Abhi-Jeeet good work!

**Comment by Abhilash107** [comment]
> > Fixed #20
> > This pull request introduces a responsive "Contact Us" page for the Sidebar website. The page has been designed to provide a smooth user experience and features an improved background for enhanced aesthetics.
> > Features:
> > 
> > 1. Fully responsive design that adapts to different screen sizes.
> > 2. Intuitive layout for users to easily reach out.
> > 3. Enhanced visual appeal with a modern background and styling
> > 
> > Screenshot 2024-10-14 161127
> > Awaiting feedback for any additional improvements or suggestions.
> 
> @Abhi-Jeeet good work!
make sure to star the repo!

**Comment by Abhi-Jeeet** [comment]
Sure !!!

**Comment by Abhilash107** [comment]
> Sure, I already star your repo!!!

if possible, please follow me.

**Comment by Abhi-Jeeet** [comment]
I started following you also.

**Pull request merged**
