### PR TITLE
implement Toggle for Sidebar Position Between Left and Right

### PR DESCRIPTION
**Pull request by MaximilianoCabreraP**
This PR updates the sidebar menu to allow it to toggle between sliding in from the left or right side when you click the header button, making the interface more dynamic and user-friendly.

### CODE REVIEW

**Comment by Abhilash107** [comment]
Hello, everyone! 👋

I am temporarily pausing the acceptance of new Issues and Pull Requests as I focus on the server side of the project. During this period, my priority will be improving the backend, performance,

While I'm excited about the upcoming changes and enhancements, I kindly ask for your patience and understanding as I work behind the scenes.

Please stay tuned for updates—once this phase is complete, I'll reopen the repository for contributions and feedback.

Thank you for your support! 🙏

Best regards,
@Abhilash107

**Comment by MaximilianoCabreraP** [comment]
Oh, could you considere to implement my feature? This could help me too with the hacktober participation. 🙏

**Comment by Abhilash107** [comment]
@MaximilianoCabreraP ok, Could you please share any screenshots of the changes made?

**Comment by MaximilianoCabreraP** [comment]
Yes, of course. I added a button (text and style are for reference only) that switches the menu sideways
image

**Pull request merged**
