### PR TITLE
FIX #21: Capitalize the first letter of dashboard and edit the title …

### LINKED ISSUE #21: Capitalize the first letter of dashboard and edit the title to sidebar
Screenshot 2024-10-14 114449

Change the dashboard to Dashboard to make it look more professional.
Also, edit the title to Sidebar instead of Document in the meta 

Pls assign this issue to me under Hactoberfest.

Thank You !

### PR DESCRIPTION
**Pull request by Devashish-Mishra-2003**
@Abhilash107 

Fixes #21 

Fixed :
1. Changed dashboard to Dashboard
2. Changed the title from Document to Sidebar

Screenshot 2024-10-14 115304

If you liked this work, please merge my pull request under Hactoberfest.

Thank You!

### CODE REVIEW

**Comment by Abhilash107** [comment]
@Devashish-Mishra-2003 Changes cannot be made directly until you are assigned.

**Comment by Abhilash107** [comment]
Ok, no worries. Let me assign that issue to you. Then, you can edit the PR description and add "fixes #issueID

**Comment by Abhilash107** [comment]
@Devashish-Mishra-2003 Hey I have assigned it to you, just add the issueID here like fixes #xyz

**Comment by Devashish-Mishra-2003** [comment]
Done.

Thank You  !

**Comment by Abhilash107** [comment]
> Done.
> 
> Thank You !

It's a good practice to mention the issue tag and always helps the maintainer to check linked PRs.

**Comment by Abhilash107** [comment]
@Devashish-Mishra-2003 The changes you have made may be marked as spam due to simple text alterations.

**Comment by Abhilash107** [comment]
@Devashish-Mishra-2003 Hey there! Don't forget to star the repository and give me a follow!

**Pull request merged**
